CREATE TABLE CONTACT(
  ID         INTEGER     NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(60) NOT NULL,
  LAST_NAME  VARCHAR(40) NOT NULL,
  BIRTH_DATE DATE,
  version    INT,
  PRIMARY KEY(ID)
);

CREATE TABLE CONTACT_TEL_DETAIL(
  ID         INT         NOT NULL AUTO_INCREMENT,
  CONTACT_ID INT         NOT NULL,
  TEL_TYPE   VARCHAR(20) NOT NULL,
  TEL_NUMBER VARCHAR(20) NOT NULL,
  version    INT,
  PRIMARY KEY (ID),
  CONSTRAINT FK_CONTACT_TEL_DETAIL_1 FOREIGN KEY(CONTACT_ID)
  REFERENCES CONTACT(ID)
);

CREATE TABLE HOBBY(
  id         VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE CONTACT_HOBBY_DETAIL(
  CONTACT_ID INT NOT NULL,
  HOBBY_ID   VARCHAR(20) NOT NULL,
  PRIMARY KEY (CONTACT_ID, HOBBY_ID),
  CONSTRAINT FK_CONTACT_HOBBY_DETAIL_1 FOREIGN KEY (CONTACT_ID)
  REFERENCES CONTACT(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CONTACT_HOBBY_DETAIL_2 FOREIGN KEY (HOBBY_ID)
  REFERENCES HOBBY(ID)
);